---
- name: requires lib-usb dev library
  become: yes
  apt:
    name: libusb-1.0-0-dev
    state: latest

- name: git fcd source
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/bobfogg/fcd.git
    dest: "{{ software_dir }}/fcd"

- name: install fcd
  become: yes
  make:
    chdir: "{{ software_dir }}/fcd"
    target: install