---
- name: ensure sensorgnome dirs exist
  become: yes
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
  with_items:
    - { path: '/dev/sensorgnome/usb' }
    - { path: '/etc/ctt/sensorgnome' }

- name: copy bootcount startup script
  become: yes
  ansible.builint.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - { src: 'files/sg-boot.service', dest: '/etc/ctt/systemd/bootcount.service' }
    - { src: 'files/sensorgnome.service', dest: '/etc/ctt/systemd/sensorgnome.service' }
    - { src: 'files/start-sensorgnome.sh', dest: '/etc/ctt/scripts/start-sensorgnome.sh' }
    - { src: 'files/usb_hub_rules.txt', dest: '/etc/ctt/sensorgnome/usb_hub_rules.txt' }

- name: link udev rules, bootcount and sensorgnome service
  become: yes
  ansible.builtin.file:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: "{{ software_dir }}/sensorgnome/udev-rules/usb-compute-hub.rules", dest: '/etc/udev/rules.d/80-sg-usb-compute.rules' }
    - { src: "{{ software_dir }}/sensorgnome/udev-rules/usb-compute-hub.rules", dest: '/etc/udev/rules.d/80-sg-usb-compute.rules' }
    - { src: '/etc/ctt/systemd/bootcount.service', dest: '/etc/systemd/system/bootcount.service' }
    - { src: '/etc/ctt/systemd/sensorgnome.service', dest: '/etc/systemd/system/sensorgnome.service' }
    - { src: '/etc/ctt/sensorgnome/usb_hub_rules.txt', dest: '/data/usb_hub_rules.txt' }

- name: enable sg boot / master systemd processes
  become: yes
  systemd:
    name: "{{ item.name }}"
    state: started
    enabled: yes
  with_items: 
    - { name: 'bootcount' }
    - { name: 'sensorgnome' }

