---
- name: git vamp-plugins
  become: yes
  become_user: ctt
  git:
    repo: https://github.com/bobfogg/vamp-plugins.git
    dest: /home/ctt/proj/vamp-plugins

- name: build vamp-plugins
  become: yes
  become_user: ctt
  make:
    chdir: /home/ctt/proj/vamp-plugins/lotek

- name: verify vamp-plugin folder exists (./.vamp)
  become: yes
  become_user: ctt 
  file:
    path: /home/ctt/.vamp
    state: directory

- name: install vamp-plugins
  become: yes
  become_user: ctt
  make:
    chdir: /home/ctt/proj/vamp-plugins/lotek
    target: install