---
- name: git vamp-plugins
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/bobfogg/vamp-plugins.git
    dest: "{{ software_dir }}/vamp-plugins"

- name: build vamp-plugins
  become: yes
  become_user: "{{ user }}"
  make:
    chdir: "{{ software_dir }}/vamp-plugins/lotek"

- name: verify vamp-plugin folder exists (./.vamp)
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ software_dir }}/.vamp"
    state: directory

- name: install vamp-plugins
  become: yes
  become_user: "{{ user }}"
  make:
    chdir: "{{ software_dir }}/vamp-plugins/lotek"
    target: install

- name: copy vamp plugin to .vamp dir
  become: yes
  ansible.builtin.file:
    src: "{{ software_dir }}/vamp-plugins/lotek/lotek-plugins.so"
    dest: "{{ software_dir }}/.vamp/lotek-plugins.so"
    state: link